### PR TITLE
distutils formatting POST data correctly now

### PR DESCRIPTION
**Pull request by johnphillips1992**
…error response if command not found

https://github.com/benliles/djangopypi/issues/56

### CODE REVIEW

**Comment by johnphillips1992** [comment]
@benliles ok I added the metadata

**Comment by johnphillips1992** [comment]
the md5 hash POST request data get was not using .strip() so it included the \r\n I fixed that and also added .strip() to the other post request data gets. tested on a local vagrant box

**Comment by johnphillips1992** [comment]
now I'm having an error with md5 hash validation when downloading

**Comment by johnphillips1992** [comment]
I think that this person has already ran into and fixed the issue: https://github.com/disqus/djangopypi/commit/cd3e999ae01eb8fb0b2e3cc74ba10f67beeaca52

 the problem stems from: https://bugs.python.org/issue10510

**Comment by johnphillips1992** [comment]
I'm going to just use disqus solution

**Comment by martinroos1** [comment]
I assume this breaks compatibility with older versions of python (those which have distutils which formats the data incorrectly)?

Could a switch be used to determine whether or not the old style parsing is required (a crude check for the raw data starting with \n for example, I'm sure there is a better way of doing this however)? In my environment, users are on varying versions of python, and requiring a python upgrade is not an option. I was hoping a solution could be found that could suit all python versions.

**Pull request closed without merging**
